name: Terraform Apply

on:
  repository_dispatch:
    types: [terraform-apply]

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.environment || 'default' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.client_payload.working_directory || '.' }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.event.client_payload.working_directory || '.' }}
        env:
          TF_VAR_environment: ${{ github.event.client_payload.environment || 'default' }} 