name: Terraform Plan

on:
  repository_dispatch:
    types: [terraform-plan]

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.environment || 'default' }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: seanparhamtaylor

      - name: Debug
        run: |
          echo "APP_ID: ${{ vars.APP_ID }}"
          echo "APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}"
          echo "INSTALLATION_ID: ${{ steps.generate-token.outputs.installation-id }}"

      - name: Debug Repository Information
        run: |
          STEPS_GENERATE_TOKEN_OUTPUTS_TOKEN=${{ steps.generate-token.outputs.token }}
          echo "Repository from payload: ${{ github.event.client_payload.repository }}"
          echo "Ref from payload: ${{ github.event.client_payload.ref }}"
          echo "Token length: ${#STEPS_GENERATE_TOKEN_OUTPUTS_TOKEN}"
          echo "Token first 4 chars: ${STEPS_GENERATE_TOKEN_OUTPUTS_TOKEN:0:4}"

      - name: Checkout (Test)
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          path: test-checkout

      - name: Checkout (Test 2)
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: seanparhamtaylor/iac-poc
          path: test-checkout-2

      - name: Checkout (Test 3)
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: seanparhamtaylor/iac-poc-api
          path: test-checkout-3
  
      - name: Checkout Terraform Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          path: terraform-code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-code

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: terraform-code
        continue-on-error: true
