name: Terraform Plan

on:
  repository_dispatch:
    types: [terraform-plan]

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.environment || 'default' }}
    env:
      TF_VAR_github_app_id: ${{ vars.APP_ID }}
      TF_VAR_github_app_pem_file: ${{ secrets.APP_PRIVATE_KEY }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Debug
        run: |
          echo "APP_ID: ${{ vars.APP_ID }}"
          echo "APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}"
          echo "INSTALLATION_ID: ${{ steps.generate-token.outputs.installation-id }}"

          echo "TF_VAR_github_app_installation_id=${{ steps.generate-token.outputs.installation-id }}" >> $GITHUB_ENV

      - name: Debug Client Payload
        run: |
          echo "Payload: ${{ toJson(github.event.client_payload) }}"

      - name: Checkout Terraform Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          path: terraform-code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-code

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: terraform-code
